sonar.projectKey=youtube
sonar.host.url=http://localhost:9000
sonar.token=sqa_b555823b3dd318b6ad5fbabc59dab890d0717e6b
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/__tests__/**, **/*.test.js, **/*.test.jsx, **/*.spec.js, **/*.spec.jsx
sonar.coverage.exclusions=**/__tests__/**, **/*.test.js, **/*.test.jsx, **/*.spec.js, **/*.spec.jsx, src/app.jsx, src/main.jsx, src/App.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info